name: Second workflow exercise
on: 
  push:
    branches:
      -  main
jobs:
  first-job:
    name: The first job of this workflow
    runs-on: ubuntu-latest
    steps:
      - name: Get Source code
        uses: actions/checkout@v4
      - name: Install dependencies and execute test
        run: npm install
      - name: Execute test
        run: npm run test
  second-job-deployment:
    name: Deploy the artifact
    needs: first-job 
    runs-on: ubuntu-latest
    steps:
      - name: Get souce code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deliver the code
        run: echo "Delivering the code to the server"
